import type { OnboardingStepDefinition } from "@/lib/onboarding-steps";

export const introductionQuestions: OnboardingStepDefinition[] = [
  { id: "plan", order: 1, type: "confirmation", required: true, title: "Är introduktionen planerad?", description: "Inledning", helpText: "Den ansvarige ska veta vem som lär upp, vilket material som ska användas och att arbetsplatsen är klar.", confirmationLabel: "Introduktionen är planerad.", content: "Exempel: fadder eller mentor är utsedd, material är skickat och passerkort finns." },
  { id: "company", order: 2, type: "task", required: true, title: "Vad behöver den nyanställde veta om företaget?", description: "Företagsinformation", helpText: "Historik, affärsidé och organisation. Använd företagets egna uppgifter.", confirmationLabel: "Vi har gått igenom företaget.", content: "Exempel: vi är ett byggföretag med 12 anställda och arbetar i Skåne." },
  { id: "hours", order: 3, type: "confirmation", required: true, title: "Har arbetstid, lön och frånvaro gåtts igenom?", description: "Arbetstid och administration", helpText: "Första dagen, ID-bricka, tider, sjukfrånvaro och ledighet.", confirmationLabel: "Arbetstid och frånvaro är genomgångna." },
  { id: "wellness", order: 4, type: "confirmation", required: false, title: "Ingår friskvård i introduktionen?", description: "Friskvård", helpText: "Företagshälsovård och friskvård, om företaget erbjuder det.", confirmationLabel: "Friskvård är genomgången." },
  { id: "safety", order: 5, type: "confirmation", required: true, title: "Har arbetsmiljön gåtts igenom?", description: "Arbetsmiljö", helpText: "Nödutgångar, första hjälpen, skyddsombud och vad som gäller vid olycka.", confirmationLabel: "Arbetsmiljön är genomgången." },
  { id: "improvement", order: 6, type: "confirmation", required: true, title: "Vet personen hur man lämnar förslag och avvikelser?", description: "Förbättring", helpText: "Förslag, tillbud och avvikelser ska kunna lämnas utan att det blir krångligt.", confirmationLabel: "Förbättring och avvikelser är genomgångna." },
  { id: "union", order: 7, type: "confirmation", required: false, title: "Ska facklig information ingå?", description: "Fackliga frågor", helpText: "Kontaktperson, om det är relevant för företaget.", confirmationLabel: "Facklig information är genomgången." },
  { id: "rules", order: 8, type: "confirmation", required: true, title: "Har ordningsreglerna gåtts igenom?", description: "Ordning", helpText: "Lokaler, städning, fikarum och vad som gäller på arbetsplatsen.", confirmationLabel: "Ordningsreglerna är genomgångna." },
  { id: "policy", order: 9, type: "confirmation", required: true, title: "Har företagets policyer gåtts igenom?", description: "Policy", helpText: "Företagets egna policyer, inte en exempeltext.", confirmationLabel: "Policyerna är genomgångna." },
  { id: "receipt", order: 10, type: "task", required: true, title: "Vilken utrustning har lämnats ut?", description: "Kvittens", helpText: "Nyckel, mobil, verktyg, kläder eller skyddsutrustning.", confirmationLabel: "Utrustningen är kvitterad.", content: "Exempel: nyckel till förrådet och varselkläder." },
  { id: "alarm", order: 11, type: "confirmation", required: true, title: "Vet personen hur larm och olycka hanteras?", description: "Larm", helpText: "Säkra platsen, hjälp och larma. Tillbud rapporteras även om ingen skadades.", confirmationLabel: "Larmrutinerna är genomgångna." },
  { id: "confirm", order: 12, type: "confirmation", required: true, title: "Har informationen gåtts igenom?", description: "Bekräftelse", helpText: "Bekräftelsen visar att informationen har lämnats. Den godkänner inte själva arbetet.", confirmationLabel: "Informationen har gåtts igenom." },
];
