import type { OnboardingStepDefinition } from "@/lib/onboarding-steps";

export interface IntroductionQuestion extends OnboardingStepDefinition {
  placeholder: string;
  examples: Record<string, string>;
}

export const introductionQuestions: IntroductionQuestion[] = [
  { id: "plan", order: 1, type: "task", required: true, title: "Är första dagarna planerade, och vem tar emot?", description: "Inledning", helpText: "Skriv datum, vem som är mentor och vad som ska hinnas första dagen. En oförberedd första dag blir en dålig introduktion.", placeholder: "Datum, mentor och vad som gås igenom dag ett", confirmationLabel: "Introduktionen är planerad.", content: "Exempel visas under fältet.", examples: { construction: "Måndag 8.00 på platsen. Erik är mentor. Skydd och kontakt till arbetsledare är klara.", cleaning: "Måndag 7.30. Objektlista och kemikalier är medskickade.", it: "Konto är skapat innan dag ett. Lisa tar emot.", healthcare: "Sekretess och brukarrutin ingår första dagen.", general: "Möte klockan 8. Mentor är utsedd. Materialet är klart." } },
  { id: "company", order: 2, type: "task", required: true, title: "Vad behöver personen veta om företaget och sitt jobb?", description: "Företaget", helpText: "En halv sida räcker: vad ni gör, vilka ni jobbar för och vad den egna rollen ansvarar för.", placeholder: "Verksamhet, kunder och den egna rollen", confirmationLabel: "Företaget är genomgånget.", content: "", examples: { construction: "Vi bygger åt privata kunder i Skåne. Platschefen leder platsen.", cleaning: "Vi städar kontor och trapphus. Objekten och vad som ingår gås igenom.", it: "Vi driftar kundernas system. Support är första kontakten.", general: "Vi berättar vad företaget gör, vilka kunderna är och vem som är chef." } },
  { id: "hours", order: 3, type: "task", required: true, title: "Vilka tider gäller, och vem tar emot sjukanmälan?", description: "Arbetstid", helpText: "Det här är pärmens funktion, inte ett lagkrav. Skriv bara det ni faktiskt gör. Belopp hämtas aktuella.", placeholder: "Tider och vem man ringer vid sjukdom", confirmationLabel: "Tider och frånvaro är genomgångna.", content: "", examples: { construction: "07.00–16.00 på plats. Sjuk anmäls till arbetsledaren före 06.30.", transport: "Kör- och vilotider gäller utöver kontorstid.", general: "08.00–16.30. Sjuk anmäls till chefen före klockan 8." } },
  { id: "wellness", order: 4, type: "task", required: false, title: "Vad gäller för friskvård, och vart vänder man sig om jobbet påverkar hälsan?", description: "Friskvård", helpText: "Skriv bidraget ni faktiskt ger, eller att ni inte har något. Hitta inte på en skattefri nivå.", placeholder: "Bidrag och vem man kontaktar", confirmationLabel: "Friskvård är genomgången.", content: "", examples: { general: "Friskvård är 2 000 kr per år. Ohälsa i jobbet tas med chefen." } },
  { id: "safety", order: 5, type: "confirmation", required: true, title: "Har faror, skyddsombud och vad man gör vid olycka gåtts igenom?", description: "Arbetsmiljö", helpText: "Visa förbandslåda och utrymning. Läs inte upp en lag. Använd er egen farolista.", placeholder: "Skyddsombud och vad man gör vid olycka", confirmationLabel: "Arbetsmiljön är genomgången.", content: "", examples: { construction: "Fall, skyddsskor och att heta arbeten kräver tillstånd.", cleaning: "Halka, lyft, kemikalier och ögondusch.", it: "Skärm, stress och vad man gör vid en incident.", general: "112, första hjälpen och vem som är skyddsombud." } },
  { id: "improvement", order: 6, type: "confirmation", required: true, title: "Vet personen hur man lämnar förslag och skriver en avvikelse?", description: "Förbättring", helpText: "Visa vem som tar emot. Det ska inte användas för att sätta dit någon.", placeholder: "Vem som tar emot förslag och avvikelser", confirmationLabel: "Förslag och avvikelser är genomgångna.", content: "", examples: { general: "Förslag lämnas till chefen. Vi tittar på orsaken och vad som hindrar att det händer igen." } },
  { id: "union", order: 7, type: "task", required: false, title: "Vart vänder man sig om ni har fackligt avtal?", description: "Fack", helpText: "Skriv kontakt, eller att ni inte har något avtal. Hitta inte på ett ombud.", placeholder: "Kontakt eller inget avtal", confirmationLabel: "Facklig information är lämnad.", content: "", examples: { general: "Inget avtal. Närmaste fråga tas med chefen." } },
  { id: "rules", order: 8, type: "confirmation", required: true, title: "Vet personen hur ni håller ordning och sorterar avfall?", description: "Ordning", helpText: "Peka på kärlen. Läs inte en kommunal föreskrift högt.", placeholder: "Kärl och vem som äger rutinen", confirmationLabel: "Ordning och sortering är genomgångna.", content: "", examples: { construction: "Spill plockas undan och transportvägar hålls fria.", general: "Var och en lämnar ytan som hen vill finna den." } },
  { id: "policy", order: 9, type: "confirmation", required: true, title: "Har era policyer gåtts igenom, och vad betyder de i jobbet?", description: "Policy", helpText: "Använd era egna policyer. Exempel i pärmen är inte era texter.", placeholder: "Vilka policyer och en vardagsmening", confirmationLabel: "Policyerna är genomgångna.", content: "", examples: { construction: "Vi stoppar arbetet om skydd saknas.", it: "Lösenord delas inte.", general: "Vi gör om jobb som blivit fel och stoppar farligt arbete." } },
  { id: "receipt", order: 10, type: "task", required: true, title: "Vilken utrustning har lämnats ut?", description: "Kvittens", helpText: "Kvittera bara det ni faktiskt lämnar. Skriv vad som gäller om något tappas.", placeholder: "Nyckel, telefon, kläder eller skydd", confirmationLabel: "Utrustningen är kvitterad.", content: "", examples: { construction: "Hjälm, skor och nyckel till boden.", it: "Dator och eget konto.", general: "Nyckel och telefon. Återlämnas när anställningen slutar." } },
  { id: "alarm", order: 11, type: "task", required: false, title: "Hur låses och larmas lokalen, och vad gör man vid falsklarm?", description: "Larm", helpText: "Skriv bara för den som får kod. Alla behöver inte kunna larma av. Svara att larm saknas om ni inte har något.", placeholder: "På, av och falsklarm, eller inget larm", confirmationLabel: "Larmrutinen är genomgången.", content: "", examples: { general: "Vi har inget larm. Sist låser." } },
  { id: "confirm", order: 12, type: "confirmation", required: true, title: "Finns namn, datum och vem som informerade?", description: "Bekräftelse", helpText: "Listan visar att introduktionen hänt. Bocka bara delar ni använder.", placeholder: "Datum och vem som informerade", confirmationLabel: "Informationen har gåtts igenom och signerats.", content: "", examples: { general: "Genomgången idag. Chefen informerade. Den anställde har signerat." } },
  { id: "followup", order: 13, type: "task", required: true, title: "När följer ni upp om personen förstått jobbet och saknar något?", description: "Uppföljning", helpText: "Boka tiden redan första dagen. Fråga vad som varit otydligt, inte bara om personen trivs.", placeholder: "Datum och vem som följer upp", confirmationLabel: "Uppföljningen är bokad.", content: "", examples: { general: "Uppföljning med chefen om två veckor. Vi fångar vad som saknas." } },
];

export function questionById(id: string) {
  return introductionQuestions.find((item) => item.id === id) ?? null;
}

export function exampleFor(id: string, industry: string) {
  const question = questionById(id);
  if (!question) return "";
  return question.examples[industry] ?? question.examples.general ?? "";
}
