import type { OnboardingStepDefinition } from "@/lib/onboarding-steps";

export interface IntroductionQuestion extends OnboardingStepDefinition {
  placeholder: string;
  examples: Record<string, string>;
}

export const introductionQuestions: IntroductionQuestion[] = [
  { id: "plan", order: 1, type: "task", required: true, title: "Är första dagarna planerade, och vem tar emot?", description: "Inledning", helpText: "Skriv datum, mentor och vad som ska hinnas dag ett. Hör till introduktionsrutinen, bevis till ISO 9001 och 45001.", placeholder: "Datum, mentor och vad som gås igenom dag ett", confirmationLabel: "Introduktionen är planerad.", content: "", examples: { general: "Möte klockan 8. Mentor är utsedd. Materialet är klart.", cleaning: "Måndag 7.30. Objektlista och kemikalier är medskickade.", construction: "Måndag 8.00 på platsen. Skydd och kontakt till arbetsledaren är klara.", electrical: "Måndag 7.00. Egenkontroller och spänningsvarning är med.", hvac: "Måndag 7.00. Verktyg och kundens tillträde är klara.", facility: "Nycklar och larmkod är förberedda innan dag ett.", transport: "Fordon och körjournal är klara. Mentor visar rundan.", manufacturing: "Omklädning och maskingenomgång är bokad.", consulting: "Kundregler och mappåtkomst är klara innan mötet.", it: "Konto är skapat innan dag ett. Mentor tar emot.", healthcare: "Sekretess och brukarrutin ingår första dagen." } },
  { id: "company", order: 2, type: "task", required: true, title: "Vad behöver personen veta om företaget och sitt jobb?", description: "Företaget", helpText: "En halv sida: vad ni gör, vilka ni jobbar för och vad rollen ansvarar för. Verksamhet och roller, ISO 9001.", placeholder: "Verksamhet, kunder och den egna rollen", confirmationLabel: "Företaget är genomgånget.", content: "", examples: { general: "Vi berättar vad företaget gör, vilka kunderna är och vem som är chef.", cleaning: "Vi städar kontor och trapphus. Objekten och vad som ingår gås igenom.", construction: "Vi bygger åt privata kunder. Platschefen leder platsen.", electrical: "Vi installerar och servar el. Arbetsledaren fördelar jobben.", hvac: "Vi monterar och servar värme och vatten. Servicechefen tar kundfrågan.", facility: "Vi sköter beståndet. Felanmälan går till driftteknikern.", transport: "Vi kör linjer och gods. Trafikledaren planerar dagen.", manufacturing: "Vi tillverkar och någon namngiven godkänner innan leverans.", consulting: "Vi gör uppdrag. Uppdragsansvarig granskar innan det går till kunden.", it: "Vi driftar kundernas system. Support är första kontakten.", healthcare: "Vi berättar vilka brukare vi har och vad som dokumenteras." } },
  { id: "hours", order: 3, type: "task", required: true, title: "Vilka tider gäller, och vem tar emot sjukanmälan?", description: "Arbetstid", helpText: "Pärmens funktion, inte ett ISO-krav. Skriv bara era tider. Belopp och sjuklön hämtas aktuella.", placeholder: "Tider och vem man ringer vid sjukdom", confirmationLabel: "Tider och frånvaro är genomgångna.", content: "", examples: { general: "08.00–16.30. Sjuk anmäls till chefen före klockan 8.", cleaning: "Tider per objekt. Sjuk anmäls till arbetsledaren före start.", construction: "07.00–16.00 på plats. Sjuk anmäls till arbetsledaren före 06.30.", electrical: "07.00–16.00. Sjuk anmäls till arbetsledaren före start.", hvac: "07.00–16.00. Sjuk anmäls till servicechefen.", facility: "Schema per fastighet. Sjuk anmäls till förvaltaren.", transport: "Kör- och vilotider gäller utöver kontorstid. Sjuk anmäls till trafikledaren.", manufacturing: "Skift enligt schema. Sjuk anmäls till produktionsledaren före skiftet.", consulting: "Flextid. Tid rapporteras till uppdragsansvarig varje fredag.", it: "Flextid. Tid rapporteras i systemet senast fredag.", healthcare: "Schema och vab samma dag till samordnaren." } },
  { id: "wellness", order: 4, type: "task", required: false, title: "Vad gäller för friskvård, och vart vänder man sig om jobbet påverkar hälsan?", description: "Friskvård", helpText: "Bidraget är ert beslut. Att ohälsa i jobbet har en mottagare hör till arbetsmiljön, ISO 45001. Hitta inte på en skattefri nivå.", placeholder: "Bidrag och vem man kontaktar", confirmationLabel: "Friskvård är genomgången.", content: "", examples: { general: "Friskvård är det belopp ni ger, eller ingen. Ohälsa i jobbet tas med chefen.", cleaning: "Företagshälsovård om riskbedömningen säger att kontroll behövs.", construction: "Företagshälsovård vid arbete med fall, damm eller buller.", electrical: "Ohälsa och elolycka tas med arbetsledaren samma dag.", hvac: "Ohälsa tas med servicechefen. Företagshälsovård om ni har avtal.", facility: "Ensamarbete och belastning tas med förvaltaren.", transport: "Trötthet och olycka tas med trafikledaren. Inte ett belopp i lagen.", manufacturing: "Buller och belastning tas med produktionsledaren.", consulting: "Enkel friskvård. Stress tas med uppdragsansvarig.", it: "Enkel friskvård. Stress och skärm tas med närmaste chef.", healthcare: "Belastning och hot tas med verksamhetschefen." } },
  { id: "safety", order: 5, type: "confirmation", required: true, title: "Har faror, skyddsombud och vad man gör vid olycka gåtts igenom?", description: "Arbetsmiljö", helpText: "Visa förbandslåda och utrymning. Använd er farolista. ISO 45001. Läs inte upp en lag.", placeholder: "Skyddsombud och vad man gör vid olycka", confirmationLabel: "Arbetsmiljön är genomgången.", content: "", examples: { general: "112, första hjälpen och vem som är skyddsombud.", cleaning: "Halka, lyft, kemikalier och var ögonduschen finns.", construction: "Fall, skyddsskor och att heta arbeten kräver tillstånd.", electrical: "Spänning, säkring och att arbete utan behörighet stoppas.", hvac: "Heta arbeten, tryck och var avstängningen sitter.", facility: "Ensamarbete, nycklar och hiss.", transport: "Lastning, trafik och vad man gör vid olycka.", manufacturing: "Maskiner, buller, hörselskydd och nödstopp.", consulting: "Skärm, stress och vem man säger till.", it: "Skärm, stress och vad man gör vid en incident.", healthcare: "Förflyttning, hot, ensamarbete och sekretess vid olycka." } },
  { id: "improvement", order: 6, type: "confirmation", required: true, title: "Vet personen hur man lämnar förslag och skriver en avvikelse?", description: "Förbättring", helpText: "Visa vem som tar emot. Det ska inte användas för att sätta dit någon. ISO 9001.", placeholder: "Vem som tar emot förslag och avvikelser", confirmationLabel: "Förslag och avvikelser är genomgångna.", content: "", examples: { general: "Förslag lämnas till chefen. Vi tittar på orsaken.", cleaning: "Missat moment hos kund skrivs till arbetsledaren.", construction: "Fel mot ritning eller tillbud sägs till platschefen samma dag.", electrical: "Felsökning som återkommer skrivs till arbetsledaren.", hvac: "Läcka eller fel montage skrivs till servicechefen.", facility: "Felanmälan som inte följts upp tas med förvaltaren.", transport: "Skada på gods skrivs till trafikledaren.", manufacturing: "Kassation skrivs till produktionsledaren.", consulting: "Fel i leverans tas med uppdragsansvarig.", it: "Incident skrivs till den som tar emot driftlarm.", healthcare: "Avvikelse kring brukare skrivs med sekretess." } },
  { id: "union", order: 7, type: "task", required: false, title: "Vart vänder man sig om ni har fackligt avtal?", description: "Fack", helpText: "Pärmens funktion, inte ett ISO-krav. Skriv kontakt eller att avtal saknas. Skyddsombud ligger i arbetsmiljöfrågan.", placeholder: "Kontakt eller inget avtal", confirmationLabel: "Facklig information är lämnad.", content: "", examples: { general: "Inget avtal. Närmaste fråga tas med chefen.", cleaning: "Kontakt eller inget avtal. Hitta inte på ett ombud.", construction: "Lokal facklig kontakt, eller inget avtal.", electrical: "Lokal kontakt, eller inget avtal.", hvac: "Lokal kontakt, eller inget avtal.", facility: "Kontakt eller inget avtal.", transport: "Kontakt för förare, eller inget avtal.", manufacturing: "Lokal klubb, eller inget avtal.", consulting: "Ofta inget avtal. Skriv det om det stämmer.", it: "Ofta inget avtal. Skriv det om det stämmer.", healthcare: "Kontakt på arbetsplatsen, eller inget avtal." } },
  { id: "rules", order: 8, type: "confirmation", required: true, title: "Vet personen hur ni håller ordning och sorterar avfall?", description: "Ordning", helpText: "Peka på kärlen. Sortering hör till ISO 14001 där ni har avfall.", placeholder: "Kärl och vem som äger rutinen", confirmationLabel: "Ordning och sortering är genomgångna.", content: "", examples: { general: "Var och en lämnar ytan som hen vill finna den.", cleaning: "Kundens sortering och egna kemikalier. Inte i samma kärl.", construction: "Spill plockas undan och transportvägar hålls fria.", electrical: "Kabelrester och emballage i rätt kärl.", hvac: "Metall, isolering och spillolja skiljs åt.", facility: "Miljörummet visas. Hyresgästens kärl rörs inte.", transport: "Spill och verkstadsavfall i märkta kärl.", manufacturing: "Kärl vid linjen. Farligt avfall separat.", consulting: "Papper och mappar. Inget kundmaterial i papperskorgen.", it: "Elektronik lämnas till den som tar emot avfallet, inte i soporna.", healthcare: "Smittförande avfall separat från hushållssopor." } },
  { id: "policy", order: 9, type: "confirmation", required: true, title: "Har era policyer gåtts igenom, och vad betyder de i jobbet?", description: "Policy", helpText: "Använd era egna policyer. Exempel i pärmen är inte era texter. ISO 9001, 14001 och 45001.", placeholder: "Vilka policyer och en vardagsmening", confirmationLabel: "Policyerna är genomgångna.", content: "", examples: { general: "Vi gör om jobb som blivit fel och stoppar farligt arbete.", cleaning: "Rätt kemikalie. Inget som skadar kunden.", construction: "Vi stoppar arbetet om skydd saknas.", electrical: "Inget spänningssatt arbete utan behörighet.", hvac: "Vi stoppar om tryck eller het yta inte är säkrad.", facility: "Fel anmäls. Energi och avfall följer rutinen.", transport: "Nykter och utvilad förare.", manufacturing: "Osäker maskin stoppas.", consulting: "Kundkrav före genväg.", it: "Lösenord delas inte.", healthcare: "Brukarens säkerhet och sekretess går före takt." } },
  { id: "receipt", order: 10, type: "task", required: true, title: "Vilken utrustning har lämnats ut?", description: "Kvittens", helpText: "Kvittera bara det ni lämnar. Skydd är det jobbet kräver, ISO 45001, inte en standardlista.", placeholder: "Nyckel, telefon, kläder eller skydd", confirmationLabel: "Utrustningen är kvitterad.", content: "", examples: { general: "Nyckel och telefon. Återlämnas när anställningen slutar.", cleaning: "Skor, handskar och nyckel till objektet.", construction: "Hjälm, skor och nyckel till boden.", electrical: "Skruvdragare, testinstrument och varsel.", hvac: "Verktyg, skor och nyckel till förrådet.", facility: "Nycklar och larmdosa.", transport: "Bilnyckel, kort och varsel.", manufacturing: "Hörselskydd, skor och egna verktyg.", consulting: "Dator. Återlämnas när uppdraget slutar.", it: "Dator och eget konto. Inget delat lösenord.", healthcare: "Arbetskläder och larm. Inga brukaruppgifter i privat telefon." } },
  { id: "alarm", order: 11, type: "singleChoice", required: false, title: "Hur låses och larmas lokalen, och vad gör man vid falsklarm?", description: "Larm", helpText: "Bara den som får kod behöver kunna larma. Svara att larm saknas om ni inte har något. Del av nödläge.", placeholder: "På, av och falsklarm, eller inget larm", confirmationLabel: "Larmrutinen är genomgången.", content: "", examples: { general: "Vi har inget larm. Sist låser.", cleaning: "Kundens larm, inte ert. Koden lämnas bara till den som ska in.", construction: "Bod och etablering låses. Ofta inget centralt larm.", electrical: "Förråd låses. Larm om lokalen har det.", hvac: "Förråd låses. Larm om lokalen har det.", facility: "Kod per hus. Inte alla får alla koder.", transport: "Verkstad och nyckelskåp. Falsklarm till bevakningen om ni har en.", manufacturing: "Port och brandlarm. Falsklarm enligt skylten.", consulting: "Kontoret låses. Larm om ni har det.", it: "Kontor och serverrum. Inte alla får serverkoden.", healthcare: "Personallarm är inte samma som brandlarm." }, options: [{ id: "no-alarm", label: "Vi har inget larm" }, { id: "has-alarm", label: "Vi har larm" }] },
  { id: "confirm", order: 12, type: "confirmation", required: true, title: "Finns namn, datum och vem som informerade?", description: "Bekräftelse", helpText: "Listan är beviset, inte ett nytt krav. Bocka bara delar ni använder. Bevis till ISO 9001 och 45001.", placeholder: "Datum och vem som informerade", confirmationLabel: "Informationen har gåtts igenom och signerats.", content: "", examples: { general: "Genomgången idag. Chefen informerade. Den anställde har signerat.", cleaning: "Objekt, kemikalier och nyckel är bockade.", construction: "Platsintroduktion och skydd är bockade.", electrical: "Behörighet och egenkontroll är bockade.", hvac: "Verktyg och hetarbete är bockade om de ingår.", facility: "Nycklar och larm är bockade.", transport: "Fordon och vilotider är bockade.", manufacturing: "Maskiner hen får köra är bockade.", consulting: "Kundkrav och sekretess är bockade.", it: "Konto och incidentrutin är bockade.", healthcare: "Sekretess och dokumentation är bockade." } },
  { id: "followup", order: 13, type: "task", required: true, title: "När följer ni upp om personen förstått jobbet och saknar något?", description: "Uppföljning", helpText: "Boka tiden redan första dagen. Fråga vad som varit otydligt. Uppföljning av kompetensen, ISO 9001.", placeholder: "Datum och vem som följer upp", confirmationLabel: "Uppföljningen är bokad.", content: "", examples: { general: "Uppföljning med chefen om två veckor. Vi fångar vad som saknas.", cleaning: "Klarar personen objektet utan mentor?", construction: "Används skyddet, och vad är otydligt på platsen?", electrical: "Vilka jobb får personen göra själv?", hvac: "Vilka servicejobb får personen ta själv?", facility: "Klarar personen rundan och felanmälan?", transport: "Körning och tidrapport stämmer.", manufacturing: "Vilka maskiner får personen köra?", consulting: "Kundmöte med stöd, sedan eget.", it: "Behörigheten är rätt. Incidentrutinen sitter.", healthcare: "Dokumentation och sekretess sitter." } },
];

export function questionById(id: string) {
  return introductionQuestions.find((item) => item.id === id) ?? null;
}

export function exampleFor(id: string, industry: string) {
  const question = questionById(id);
  if (!question) return "";
  return question.examples[industry] ?? question.examples.general ?? "";
}
